spring.application.name=Unbind

spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XEPDB1
spring.datasource.username=system
spring.datasource.password=unbind1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true


server.port = 80

# Spring DevTools (자동 리로드, 서버 재시작) 설정

spring.devtools.livereload.enabled=true

# 코드 변경 시 서버 자동 재시작
spring.devtools.restart.enabled=true

# 타임리프 캐시 비활성화 (HTML 파일 수정 시 바로 변경사항 확인할 수 있도록)
spring.thymeleaf.cache=false

# 로그 레벨 지정
logging.level.edu.kh.demo=debug